### ISSUE TITLE
 dkim=permerror reason="unsupported signature algorithm" by verifier.port25.com #13 opened 2 hours ago by Sanzo-Miyazawa

### ISSUE THREAD

**Issue by Sanzo-Miyazawa** [sdgathman/milter#3]
I cannot figure out what is wrong in my setting for DKIM. I need your help.
dkimpy-milter (1.2.2-1) is used for DKIM signature and verification.

                Sanzo Miyazawa

=========================
Email arrived at [check-auth@verifier.port25.com](mailto:check-auth@verifier.port25.com) and identified as
dkim=permerror reason="unsupported signature algorithm".

Return-Path: [miyazawa@sanzo.org](mailto:miyazawa@sanzo.org)
Received: from mail01.SiriusCloud.jp (219.118.72.1) by verifier.port25.com id h2guq82p2toj for [check-auth@verifier.port25.com](mailto:check-auth@verifier.port25.com); Sun, 4 Sep 2022
05:54:44 +0000 (envelope-from [miyazawa@sanzo.org](mailto:miyazawa@sanzo.org))
Authentication-Results: verifier.port25.com; spf=pass smtp.mailfrom=[miyazawa@sanzo.org](mailto:miyazawa@sanzo.org);
iprev=pass (matches mail01.SiriusCloud.jp) policy.iprev=219.118.72.1;
dkim=permerror reason="unsupported signature algorithm" ;
dkim=fail reason="signature doesn't verify"
Received: from smi72700k.sanzo.org (61-213-47-254.catv296.ne.jp [61.213.47.254])
(using TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits))
(No client certificate requested)
(Authenticated sender: [sanzo-and-fumiko.miyazawa@catv296.ne.jp](mailto:sanzo-and-fumiko.miyazawa@catv296.ne.jp))
by access01.SiriusCloud.jp (Postfix) with ESMTPSA id 4ML17l1hvRz35vG7h
for [check-auth@verifier.port25.com](mailto:check-auth@verifier.port25.com); Sun, 4 Sep 2022 14:54:43 +0900 (JST)
DKIM-Signature: v=1; a=ed25519-sha256; c=relaxed/relaxed; d=sanzo.org;
i=@sanzo.org; q=dns/txt; s=dkim-ed25519; t=1662270880; h=date : from :
message-id : to : subject : content-type : mime-version :
content-transfer-encoding : from;
bh=47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=;
b=2ne23XnmFelQLySuMfq1zX7I1KQt3GAIx4TIKd5aicfPac8dfJmMEi4+wg1Sk2A8Le5om
DNTCIYzeIypNX8ICg==
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=sanzo.org;
i=@sanzo.org; q=dns/txt; s=dkim-rsa; t=1662270880; h=date : from :
message-id : to : subject : content-type : mime-version :
content-transfer-encoding : from;
bh=47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=;
b=qQRcdkksJwhJbJAypV9ZT8wRK0KKCoZ8AVu0VfSdG/L931iERNxozCUXF3UVnha35ws8x
+TlfnBCgCuwF4d32Gxr7f7yIHzXHpVZ5QK0WnZQ0gZ1MJ2IVnrxq4JIR+rMn1LyE2CGB2xD
MG9Z4gOVEB5N3qFt8/zB7UVejSZgOf7Vg9e1ztvxHRrqcfiTYhXnjePLaYrfr3LOQNB8P5O
6OUBgGwKQT9UehYAleTH587qZcaOGhYM0k1VLQCh6RtbPVC0ZXf2//PBAd6B7DCg4ACLN8Z
SpO7EhrRPjLJ4TkRVq3Fw6WjuKIvkxMCTJLd1chn3vdL5fn8+HhQO5SIdpVQ==
Received: from smi72700k.sanzo.org (miyazawa@ip6-localhost [127.0.0.1])
by smi72700k.sanzo.org (8.15.2/8.15.2/Debian-22) with ESMTPS id 2845sedi809535
(version=TLSv1.3 cipher=TLS_AES_256_GCM_SHA384 bits=256 verify=NOT)
for [check-auth@verifier.port25.com](mailto:check-auth@verifier.port25.com); Sun, 4 Sep 2022 14:54:40 +0900
Received: (from miyazawa@localhost)
by smi72700k.sanzo.org (8.15.2/8.15.2/Submit) id 2845se43809534;
Sun, 4 Sep 2022 14:54:40 +0900
Date: Sun, 4 Sep 2022 14:54:40 +0900
From: Sanzo Miyazawa [miyazawa@sanzo.org](mailto:miyazawa@sanzo.org)
Message-Id: [202209040554.2845se43809534@smi72700k.sanzo.org](mailto:202209040554.2845se43809534@smi72700k.sanzo.org)
To: [check-auth@verifier.port25.com](mailto:check-auth@verifier.port25.com)
Subject:
Content-Type: text/plain; charset=UTF-8
MIME-Version: 1.0
Content-Transfer-Encoding: 8bit
X-Virus-Scanned: clamav-milter 0.103.6 at smi72700k
X-Virus-Status: Clean

**Comment by sdgathman** [comment]
There are two sigs in the email.  The key for the last one encountered was:
`dkim-ed25519._domainkey.sanzo.org descriptive text "v=DKIM1; k=ed25519; p=U/SgqqBg5r+fFvcjvd0VFOUlRySFovzCrkTlfA8vNXo="`
The key for the previous one was:
`dkim-rsa._domainkey.sanzo.org descriptive text "v=DKIM1; k=rsa; h=sha256; p=" "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3LQiBHBTbMcZ9zgJWcO6Kwi42/3x1x/sSFBH7VmHW93nrU8XFwWJXcTW9RSMkwqOGgA4Io2bqKl+X9q+Scor/Gpi2mv88BBoa6GVQ4CD/qBY6vjU+M7llQPuuAP6XPn/uLB8KNjGO+YdwUw6mdRnndTQ" "MG3DcgVf7hRXxDlTmTFcf2/bRwP3F/u0kLVOK8fMF7pDtP1M4/8Ccp34lUGpKWQwTTFU1AMve+apxgh9eRjM9O+fe+llyHq9BcjOrtsuIndX4jwEim47i78quZozbDX7PLT5CXKqQvuhS6+zkUYdNqqIYlupTlQHl6xPwrZlBQYeJl93CgmhYNCKtyan4wIDAQAB"`

dkimpy doesn't seem to support ed25519.  But if that is in an update to the standard, it should.  Also, when there are multiple sigs, should it evalutate more of them, hoping one will pass?  Maybe all for the same domain?  @kitterma

**Comment by kitterma** [comment]
On October 13, 2022 4:48:11 PM UTC, "Stuart D. Gathman" ***@***.***> wrote:
>There are two sigs in the email.  The key for the last one encountered was:
>`dkim-ed25519._domainkey.sanzo.org descriptive text "v=DKIM1; k=ed25519; p=U/SgqqBg5r+fFvcjvd0VFOUlRySFovzCrkTlfA8vNXo="`
>The key for the previous one was:
>`dkim-rsa._domainkey.sanzo.org descriptive text "v=DKIM1; k=rsa; h=sha256; p=" "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3LQiBHBTbMcZ9zgJWcO6Kwi42/3x1x/sSFBH7VmHW93nrU8XFwWJXcTW9RSMkwqOGgA4Io2bqKl+X9q+Scor/Gpi2mv88BBoa6GVQ4CD/qBY6vjU+M7llQPuuAP6XPn/uLB8KNjGO+YdwUw6mdRnndTQ" "MG3DcgVf7hRXxDlTmTFcf2/bRwP3F/u0kLVOK8fMF7pDtP1M4/8Ccp34lUGpKWQwTTFU1AMve+apxgh9eRjM9O+fe+llyHq9BcjOrtsuIndX4jwEim47i78quZozbDX7PLT5CXKqQvuhS6+zkUYdNqqIYlupTlQHl6xPwrZlBQYeJl93CgmhYNCKtyan4wIDAQAB"`
>
>dkimpy doesn't seem to support ed25519.  But if that is in an update to the standard, it should.  Also, when there are multiple sigs, should it evalutate more of them, hoping one will pass?  Maybe all for the same domain?  @kitterma
>

It does.  If called correctly dkimpy will evaluate multiple signatures.

Scott K

**Comment by kitterma** [comment]
I use dkimpy-milter with ed25119 all the time.  Please raise this here:

https://answers.launchpad.net/dkimpy-milter

**Comment by sdgathman** [comment]
Moved to dkimpy-milter on launchpad.net
